version: '3.4'

services:

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - ./docker/elasticsearch-data:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always

  gateway:
    container_name: gateway
    ports:
      - "5000:5000"
    restart: always

  identity:
    container_name: identity
    ports:
      - "5200:5200"
    depends_on:
      - redis
      - rabbitmq
    restart: always

  sysapi:
    container_name: sysapi
    ports:
      - "5002:5002"
    depends_on:
      - redis
      - rabbitmq
    restart: always

  wfapi:
    container_name: wfapi
    ports:
      - "5003:5003"
    depends_on:
      - redis
      - rabbitmq
    restart: always

  weixinapi:
    container_name: weixinapi
    ports:
      - "5004:5004"
    depends_on:
      - redis
      - rabbitmq
    restart: always

  oaapi:
    container_name: oaapi
    ports:
      - "5006:5006"
    depends_on:
      - redis
      - rabbitmq
    restart: always
