version: '3.4'

services:

  gateway:
    build:
      context: .
      dockerfile: src/ApiGateways/MsSystem.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
 
  identity:
    build:
      context: .
      dockerfile: src/Services/Identity/MsSystem.Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
 
  sysapi:
    build:
      context: .
      dockerfile: src/Services/System/MsSystem.Sys.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_DB=mssystem
      - MYSQL_USER=root
      - MYSQL_PASS=123456
      - MYSQL_TCP_PORT=3306
      - MYSQL_HOST=192.168.178.81
      - MYSQL_LOG_DB=mssystemlog
      - MYSQL_LOG_USER=root
      - MYSQL_LOG_PASS=123456
      - MYSQL_LOG_TCP_PORT=3306
      - MYSQL_LOG_HOST=192.168.178.81

  weixinapi:
    build:
      context: .
      dockerfile: src/Services/Weixin/MsSystem.Weixin.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_DB=mssystem
      - MYSQL_USER=root
      - MYSQL_PASS=123456
      - MYSQL_TCP_PORT=3306
      - MYSQL_HOST=192.168.178.81

  wfapi:
    build:
      context: .
      dockerfile: src/Services/WorkFlow/MsSystem.WF.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_DB=mssystem
      - MYSQL_USER=root
      - MYSQL_PASS=123456
      - MYSQL_TCP_PORT=3306
      - MYSQL_HOST=192.168.178.81

  oaapi:
    build:
      context: .
      dockerfile: src/Services/OA/MsSystem.OA.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_DB=mssystem
      - MYSQL_USER=root
      - MYSQL_PASS=123456
      - MYSQL_TCP_PORT=3306
      - MYSQL_HOST=192.168.178.81

