version: '3.4'

services:
  
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "/data/docker/mysql/conf/my.cnf:/etc/my.cnf"
      - "/data/docker/mysql/init:/docker-entrypoint-initdb.d/"
    restart: always

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  gateway:
    image: registry.cn-hangzhou.aliyuncs.com/wangmaosheng/gateway
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - identity
      - oaapi
      - sysapi
      - wfapi

  identity:
    image: registry.cn-hangzhou.aliyuncs.com/wangmaosheng/identity
    container_name: identity
    ports:
      - "5200:5200"
    depends_on:
      - mysql
      - rabbitmq

  oaapi:
    image: registry.cn-hangzhou.aliyuncs.com/wangmaosheng/oaapi
    container_name: oaapi
    ports:
      - "5006:5006"
    depends_on:
      - mysql
      - rabbitmq

  sysapi:
    image: registry.cn-hangzhou.aliyuncs.com/wangmaosheng/sysapi
    container_name: sysapi
    ports:
      - "5002:5002"
    depends_on:
      - mysql
      - rabbitmq

  wfapi:
    image: registry.cn-hangzhou.aliyuncs.com/wangmaosheng/wfapi
    container_name: wfapi
    ports:
      - "5003:5003"
    depends_on:
      - mysql
      - rabbitmq

  web:
    image: registry.cn-hangzhou.aliyuncs.com/wangmaosheng/web
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - gateway